### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by xeelee1024** [hellojukay/with-env#1]
为了使用方便，我把with-env.exe重命名为了ppp.exe，并且把ppp.exe和.env文件直接丢到了C:\Windows\System32，这样我可以在任意路径cmd下调用ppp命令。此时bug出现了:
cmd当前所在路径是C:\Windows\System32时，一切正常。
cmd当前所在路径是其它路径时，ppp失效，并不能达到效果。
ppp curl www.google.com
提示如下：
curl: (28) Failed to connect to www.google.com port 80 after 21208 ms: Timed out
"exit status 28"

**Comment by hellojukay** [comment]
@vip123456789 你好，`.env`文件只能放在2个地方，一个是当前所在路径路径，另外一个是放在用户的家目录，我建议你把 `.env`文件放在你的家目录，这样在任何地方执行命令都没有问题。如果2个地方都放了，是合并效果，并且当前路径的优先级更高。关于 `.env`文件的路径，在项目的 README 中有介绍。

**Comment by xeelee1024** [comment]
好的，多谢回复。受你的启发，我写了个简单的批处理，实现了同样的效果，用着也还不错，不过只支持win。
https://github.com/vip123456789/ppp

**Comment by hellojukay** [comment]
> 实现了同样的效果

@vip123456789 干得漂亮，如果你的问题已经解决了，我将关闭这个 issue , 后面问题可以随时在打开。
